#include "Transmitter.h"

#include "DACService.h"
#include <string.h>

#define TRANSMITTER_SAMPLE_COUNT 2048U
#define TRANSMITTER_BIAS 2048U
#define TRANSMITTER_SINGLE_LENGTH 8U
#define TRANSMITTER_PULSE_HIGH 4048U
#define TRANSMITTER_PULSE_LOW 48U
#define TRANSMITTER_BARKER13_LENGTH 104U
#define TRANSMITTER_BARKER13_INVERTED_MIN 148U
#define TRANSMITTER_BARKER13_INVERTED_MAX 3948U

static const uint16_t transmitter_single_waveform[TRANSMITTER_SAMPLE_COUNT] = {
    TRANSMITTER_BIAS, TRANSMITTER_PULSE_HIGH, TRANSMITTER_BIAS, TRANSMITTER_PULSE_LOW,
    TRANSMITTER_BIAS, TRANSMITTER_PULSE_HIGH, TRANSMITTER_BIAS, TRANSMITTER_PULSE_LOW,
    [TRANSMITTER_SINGLE_LENGTH ... TRANSMITTER_SAMPLE_COUNT - 1U] = TRANSMITTER_BIAS
};

#define TRANSMITTER_BARKER_POSITIVE_CHIP \
    TRANSMITTER_BIAS, TRANSMITTER_PULSE_HIGH, TRANSMITTER_BIAS, TRANSMITTER_PULSE_LOW, \
    TRANSMITTER_BIAS, TRANSMITTER_PULSE_HIGH, TRANSMITTER_BIAS, TRANSMITTER_PULSE_LOW
#define TRANSMITTER_BARKER_NEGATIVE_CHIP \
    TRANSMITTER_BIAS, TRANSMITTER_BARKER13_INVERTED_MIN, TRANSMITTER_BIAS, TRANSMITTER_BARKER13_INVERTED_MAX, \
    TRANSMITTER_BIAS, TRANSMITTER_BARKER13_INVERTED_MIN, TRANSMITTER_BIAS, TRANSMITTER_BARKER13_INVERTED_MAX

static const uint16_t transmitter_barker13_waveform[TRANSMITTER_SAMPLE_COUNT] = {
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_NEGATIVE_CHIP,
    TRANSMITTER_BARKER_NEGATIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_NEGATIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    TRANSMITTER_BARKER_NEGATIVE_CHIP,
    TRANSMITTER_BARKER_POSITIVE_CHIP,
    [TRANSMITTER_BARKER13_LENGTH ... TRANSMITTER_SAMPLE_COUNT - 1U] = TRANSMITTER_BIAS
};

static uint16_t transmitter_samples[TRANSMITTER_SAMPLE_COUNT]
    __attribute__((aligned(32)));

void Transmitter_Init(void)
{
    (void)memcpy(transmitter_samples, transmitter_single_waveform, sizeof(transmitter_samples));

    DACService_Init(transmitter_samples, TRANSMITTER_SAMPLE_COUNT);
}

void Transmitter_SetPulseType(Transmitter_PulseType pulse_type)
{
    if (pulse_type == TRANSMITTER_PULSE_BARKER13)
    {
        (void)memcpy(transmitter_samples, transmitter_barker13_waveform, sizeof(transmitter_samples));
    }
    else
    {
        (void)memcpy(transmitter_samples, transmitter_single_waveform, sizeof(transmitter_samples));
    }
}